platform :ios, '11.1'
inhibit_all_warnings!
use_frameworks!

target 'TICoreNFCExtensions_Example' do
  pod 'TICoreNFCExtensions', :path => '../'

  target 'TICoreNFCExtensions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
